/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Outlines, useGLTF, useTexture } from "@react-three/drei";
import { type ThreeEvent, useThree } from "@react-three/fiber";
import { RapierRigidBody, RigidBody } from "@react-three/rapier";
import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

const AIM_MIN_DISTANCE = 0.05;
const AIM_POWER_NORMALIZATION_DISTANCE = 16;
const AIM_VISIBLE_ARROW_MAX_LENGTH = 18;

export interface BallAimDraft {
  dragStart: { x: number; y: number; z: number };
  dragCurrent: { x: number; y: number; z: number };
  shotVector: { x: number; y: number; z: number };
  normalizedDirection: { x: number; y: number; z: number };
  pullDistance: number;
  normalizedPower: number;
}

interface BallProps {
  position?: [number, number, number];
  interactive?: boolean;
  renderOnly?: boolean;
  aimEnabled?: boolean;
  onAimChange?: (draft: BallAimDraft | null) => void;
  onAimRelease?: (draft: BallAimDraft) => void;
}

type GLTFResult = GLTF & {
  nodes: {
    Ball: THREE.Mesh;
  };
  materials: Record<string, THREE.Material>;
};

type PointerCaptureTarget = {
  releasePointerCapture(pointerId: number): void;
  setPointerCapture(pointerId: number): void;
};

function AimArrow({
  position,
  quaternion,
  length,
  shaftTexture,
  headTexture,
  tipGlowTexture,
}: {
  position: [number, number, number];
  quaternion: THREE.Quaternion;
  length: number;
  shaftTexture: THREE.Texture;
  headTexture: THREE.Texture;
  tipGlowTexture: THREE.Texture;
}) {
  const shaftLength = Math.max(2.4, length);
  const shaftWidth = 3.55;
  const connectorLength = Math.min(2.4, shaftLength * 0.22);
  const headSize = 6.3;
  const headCenterY = shaftLength - connectorLength * 0.55 + headSize * 0.08;
  const tipGlowY = headCenterY + headSize * 0.1;

  return (
    <group position={position} quaternion={quaternion}>
      <mesh position={[0, shaftLength / 2 + 0.15, 0.02]}>
        <planeGeometry args={[shaftWidth * 1.35, shaftLength + 1.2]} />
        <meshBasicMaterial
          map={shaftTexture}
          transparent
          opacity={0.22}
          depthWrite={false}
          side={THREE.DoubleSide}
          toneMapped={false}
          blending={THREE.AdditiveBlending}
        />
      </mesh>
      <mesh position={[0, shaftLength / 2, 0.03]}>
        <planeGeometry args={[shaftWidth, shaftLength]} />
        <meshBasicMaterial
          map={shaftTexture}
          transparent
          depthWrite={false}
          side={THREE.DoubleSide}
          toneMapped={false}
        />
      </mesh>
      <mesh position={[0, shaftLength - connectorLength / 2, 0.035]}>
        <planeGeometry args={[shaftWidth * 0.92, connectorLength]} />
        <meshBasicMaterial
          map={shaftTexture}
          transparent
          opacity={0.92}
          depthWrite={false}
          side={THREE.DoubleSide}
          toneMapped={false}
        />
      </mesh>
      <mesh position={[0, tipGlowY, 0.02]}>
        <planeGeometry args={[headSize * 1.26, headSize * 1.26]} />
        <meshBasicMaterial
          map={tipGlowTexture}
          transparent
          opacity={0.6}
          depthWrite={false}
          side={THREE.DoubleSide}
          toneMapped={false}
          blending={THREE.AdditiveBlending}
        />
      </mesh>
      <mesh position={[0, headCenterY, 0.025]}>
        <planeGeometry args={[headSize * 1.18, headSize * 1.18]} />
        <meshBasicMaterial
          map={headTexture}
          transparent
          opacity={0.42}
          depthWrite={false}
          side={THREE.DoubleSide}
          toneMapped={false}
          blending={THREE.AdditiveBlending}
        />
      </mesh>
      <mesh position={[0, headCenterY, 0.04]}>
        <planeGeometry args={[headSize, headSize]} />
        <meshBasicMaterial
          map={headTexture}
          transparent
          depthWrite={false}
          side={THREE.DoubleSide}
          toneMapped={false}
        />
      </mesh>
    </group>
  );
}

export function Ball({
  position = [0, 112, 0],
  interactive = true,
  renderOnly = false,
  aimEnabled = false,
  onAimChange,
  onAimRelease,
}: BallProps) {
  const { nodes } = useGLTF(
    "/models/in-game/Ball/Ball.glb",
  ) as unknown as GLTFResult;
  const [shaftTexture, headTexture, tipGlowTexture] = useTexture([
    "/field/aim-arrow-shaft.svg",
    "/field/aim-arrow-head.svg",
    "/field/aim-arrow-tip-glow.svg",
  ]);

  const rigidBodyRef = useRef<RapierRigidBody>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState<THREE.Vector3 | null>(null);
  const [dragCurrent, setDragCurrent] = useState<THREE.Vector3 | null>(null);
  const { camera } = useThree();

  useEffect(() => {
    shaftTexture.colorSpace = THREE.SRGBColorSpace;
    headTexture.colorSpace = THREE.SRGBColorSpace;
    tipGlowTexture.colorSpace = THREE.SRGBColorSpace;
    shaftTexture.wrapS = THREE.ClampToEdgeWrapping;
    shaftTexture.wrapT = THREE.RepeatWrapping;
    headTexture.wrapS = THREE.ClampToEdgeWrapping;
    headTexture.wrapT = THREE.ClampToEdgeWrapping;
    tipGlowTexture.wrapS = THREE.ClampToEdgeWrapping;
    tipGlowTexture.wrapT = THREE.ClampToEdgeWrapping;
  }, [headTexture, shaftTexture, tipGlowTexture]);

  const buildAimDraft = (
    start: THREE.Vector3,
    current: THREE.Vector3,
  ): BallAimDraft | null => {
    const shotVector = new THREE.Vector3().subVectors(start, current);
    const pullDistance = shotVector.length();
    if (pullDistance < AIM_MIN_DISTANCE) {
      return null;
    }

    const normalizedDirection = shotVector.clone().normalize();
    return {
      dragStart: { x: start.x, y: start.y, z: start.z },
      dragCurrent: { x: current.x, y: current.y, z: current.z },
      shotVector: { x: shotVector.x, y: shotVector.y, z: shotVector.z },
      normalizedDirection: {
        x: normalizedDirection.x,
        y: normalizedDirection.y,
        z: normalizedDirection.z,
      },
      pullDistance,
      normalizedPower: Math.min(
        1,
        pullDistance / AIM_POWER_NORMALIZATION_DISTANCE,
      ),
    };
  };

  const handlePointerDown = (e: ThreeEvent<PointerEvent>) => {
    if (!interactive && !aimEnabled) return;
    // Prevent camera controls from taking over
    e.stopPropagation();

    // In React Three Fiber, event.point is the 3D interaction point
    // using the event's ray intersection
    if (rigidBodyRef.current && !renderOnly) {
      // Stop the ball momentarily to aim? Optional, but helpful.
      rigidBodyRef.current.setLinvel({ x: 0, y: 0, z: 0 }, true);
      rigidBodyRef.current.setAngvel({ x: 0, y: 0, z: 0 }, true);
    }

    setIsDragging(true);
    setDragStart(e.point.clone());
    setDragCurrent(e.point.clone());
    onAimChange?.(null);

    // Capture pointer to track outside mesh
    (e.target as unknown as PointerCaptureTarget).setPointerCapture(
      e.pointerId,
    );
  };

  const handlePointerMove = (e: ThreeEvent<PointerEvent>) => {
    if (!interactive && !aimEnabled) return;
    if (!isDragging || !dragStart) return;

    // We need to raycast to a "virtual floor" plane at the ball's height
    // to get consistent dragging even if we move off the ball mesh
    const floorPlane = new THREE.Plane(
      new THREE.Vector3(0, 1, 0),
      -dragStart.y,
    );
    const raycaster = new THREE.Raycaster();
    raycaster.setFromCamera(e.pointer, camera);
    const intersectPoint = new THREE.Vector3();

    // Check intersection with our horizontal plane
    if (raycaster.ray.intersectPlane(floorPlane, intersectPoint)) {
      setDragCurrent(intersectPoint);
      onAimChange?.(buildAimDraft(dragStart, intersectPoint));
    }
  };

  const handlePointerUp = (e: ThreeEvent<PointerEvent>) => {
    if (!interactive && !aimEnabled) return;
    if (!isDragging || !dragStart || !dragCurrent) return;

    setIsDragging(false);
    (e.target as unknown as PointerCaptureTarget).releasePointerCapture(
      e.pointerId,
    );

    const aimDraft = buildAimDraft(dragStart, dragCurrent);

    if (interactive && rigidBodyRef.current && !renderOnly && aimDraft) {
      const impulse = new THREE.Vector3(
        aimDraft.shotVector.x,
        aimDraft.shotVector.y,
        aimDraft.shotVector.z,
      ).multiplyScalar(10.0);
      impulse.y = Math.abs(impulse.y) * 0.1;
      rigidBodyRef.current.applyImpulse(impulse, true);
    }

    if (aimDraft) {
      onAimRelease?.(aimDraft);
    } else {
      onAimChange?.(null);
    }

    setDragStart(null);
    setDragCurrent(null);
  };

  // Calculate arrow direction and length
  const arrowData = useMemo(() => {
    if (!isDragging || !dragStart || !dragCurrent) return null;

    // Direction from dragCurrent (pull position) to dragStart (ball position)
    // This shows where the ball will go
    const direction = new THREE.Vector3().subVectors(dragStart, dragCurrent);
    let length = direction.length();

    // Minimum length to show arrow
    if (length < 0.1) return null;
    if (length > AIM_VISIBLE_ARROW_MAX_LENGTH)
      length = AIM_VISIBLE_ARROW_MAX_LENGTH;

    direction.normalize();
    shaftTexture.repeat.set(1, Math.max(1, length / 7.5));

    // Calculate rotation to point in the direction
    const quaternion = new THREE.Quaternion().setFromUnitVectors(
      new THREE.Vector3(0, 1, 0), // Arrow points up by default
      direction,
    );

    return {
      position: dragStart,
      direction,
      length,
      quaternion,
    };
  }, [dragCurrent, dragStart, isDragging, shaftTexture]);

  if (renderOnly) {
    return (
      <group dispose={null} position={position} scale={0.5}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ball.geometry}
          material={nodes.Ball.material}
          onPointerDown={aimEnabled ? handlePointerDown : undefined}
          onPointerMove={aimEnabled ? handlePointerMove : undefined}
          onPointerUp={aimEnabled ? handlePointerUp : undefined}
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
        {aimEnabled && (
          <mesh
            onPointerDown={handlePointerDown}
            onPointerMove={handlePointerMove}
            onPointerUp={handlePointerUp}
          >
            <sphereGeometry args={[5, 16, 16]} />
            <meshBasicMaterial transparent opacity={0} depthWrite={false} />
          </mesh>
        )}
        {arrowData && (
          <AimArrow
            position={[
              arrowData.position.x + 0.1 - position[0],
              arrowData.position.y - position[1],
              arrowData.position.z - position[2],
            ]}
            quaternion={arrowData.quaternion}
            length={arrowData.length}
            shaftTexture={shaftTexture}
            headTexture={headTexture}
            tipGlowTexture={tipGlowTexture}
          />
        )}
      </group>
    );
  }

  return (
    <group dispose={null}>
      <RigidBody
        position={position}
        scale={0.5}
        ref={rigidBodyRef}
        colliders="ball"
        restitution={0.8}
        friction={1.0}
        linearDamping={0.5}
        angularDamping={0.5}
        name="ball"
        type={interactive ? "dynamic" : "fixed"}
        gravityScale={interactive ? 1 : 0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ball.geometry}
          material={nodes.Ball.material}
          onPointerDown={interactive ? handlePointerDown : undefined}
          onPointerMove={interactive ? handlePointerMove : undefined}
          onPointerUp={interactive ? handlePointerUp : undefined}
          // No position prop needed - mesh follows RigidBody automatically
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
      </RigidBody>

      {/* Arrow indicator showing shot direction and strength */}
      {arrowData && (
        <AimArrow
          position={[
            arrowData.position.x + 0.1,
            arrowData.position.y,
            arrowData.position.z,
          ]}
          quaternion={arrowData.quaternion}
          length={arrowData.length}
          shaftTexture={shaftTexture}
          headTexture={headTexture}
          tipGlowTexture={tipGlowTexture}
        />
      )}
    </group>
  );
}
