/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Billboard, Outlines, useGLTF } from "@react-three/drei";
import { type ThreeEvent, useThree } from "@react-three/fiber";
import { RapierRigidBody, RigidBody } from "@react-three/rapier";
import { type RefObject, useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import { BALL_MODEL_REGISTRATION } from "../../../match/ball-registration";
import {
  type BallAimDraft,
  buildBallAimDraft,
} from "../../../match/kick-gesture";
import {
  type KickControlEnvelope,
  visibleKickPowerRatio,
} from "../../../match/kick-input";

// The gesture can travel beyond the visible arrow so a full-strength touch pull
// remains reachable without driving the global power scale outside the camera.
const AIM_VISIBLE_ARROW_MAX_LENGTH = 12;
const BALL_READABILITY_OUTLINE = "#dffcff";

function BallReadabilityIndicator() {
  return (
    <Billboard follow>
      <mesh renderOrder={4}>
        <ringGeometry
          args={[
            BALL_MODEL_REGISTRATION.readabilityIndicatorInnerRadiusM,
            BALL_MODEL_REGISTRATION.readabilityIndicatorOuterRadiusM,
            32,
          ]}
        />
        <meshBasicMaterial
          color={BALL_READABILITY_OUTLINE}
          transparent
          opacity={0.55}
          depthTest={false}
          depthWrite={false}
          side={THREE.DoubleSide}
          toneMapped={false}
          blending={THREE.AdditiveBlending}
        />
      </mesh>
    </Billboard>
  );
}

export type { BallAimDraft } from "../../../match/kick-gesture";

interface BallProps {
  position?: [number, number, number];
  interactive?: boolean;
  renderOnly?: boolean;
  aimEnabled?: boolean;
  aimDraft?: BallAimDraft | null;
  kickControlEnvelope?: KickControlEnvelope | null;
  onAimChange?: (draft: BallAimDraft | null) => void;
  onAimRelease?: (draft: BallAimDraft) => void;
  renderGroupRef?: RefObject<THREE.Group | null>;
}

type GLTFResult = GLTF & {
  nodes: {
    Ball: THREE.Mesh;
  };
  materials: Record<string, THREE.Material>;
};

type PointerCaptureTarget = {
  releasePointerCapture(pointerId: number): void;
  setPointerCapture(pointerId: number): void;
};

function AimArrow({
  position,
  quaternion,
  length,
}: {
  position: [number, number, number];
  quaternion: THREE.Quaternion;
  length: number;
}) {
  const arrowLength = Math.max(2.4, length);
  const geometry = useMemo(() => {
    const headLength = THREE.MathUtils.clamp(arrowLength * 0.3, 1, 3.2);
    const headBaseY = arrowLength - headLength;
    const shaftHalfWidth = THREE.MathUtils.clamp(
      arrowLength * 0.07,
      0.45,
      0.85,
    );
    const headHalfWidth = THREE.MathUtils.clamp(
      arrowLength * 0.13,
      shaftHalfWidth * 1.7,
      1.6,
    );
    const silhouette = new THREE.Shape();
    silhouette.moveTo(-shaftHalfWidth, 0);
    silhouette.lineTo(-shaftHalfWidth, headBaseY);
    silhouette.lineTo(-headHalfWidth, headBaseY);
    silhouette.lineTo(0, arrowLength);
    silhouette.lineTo(headHalfWidth, headBaseY);
    silhouette.lineTo(shaftHalfWidth, headBaseY);
    silhouette.lineTo(shaftHalfWidth, 0);
    silhouette.closePath();
    return new THREE.ShapeGeometry(silhouette);
  }, [arrowLength]);

  useEffect(() => () => geometry.dispose(), [geometry]);

  return (
    <group position={position} quaternion={quaternion}>
      <mesh
        geometry={geometry}
        position={[0, 0, 0.02]}
        scale={[1.28, 1, 1]}
        renderOrder={1}
      >
        <meshBasicMaterial
          color="#ff58f3"
          transparent
          opacity={0.34}
          depthTest={false}
          depthWrite={false}
          side={THREE.DoubleSide}
          toneMapped={false}
          blending={THREE.AdditiveBlending}
        />
      </mesh>
      <mesh geometry={geometry} position={[0, 0, 0.03]} renderOrder={2}>
        <meshBasicMaterial
          color="#ff4ff0"
          transparent
          opacity={0.96}
          depthTest={false}
          depthWrite={false}
          side={THREE.DoubleSide}
          toneMapped={false}
        />
      </mesh>
      <mesh
        geometry={geometry}
        position={[0, arrowLength * 0.035, 0.04]}
        scale={[0.48, 0.9, 1]}
        renderOrder={3}
      >
        <meshBasicMaterial
          color="#fff8ff"
          transparent
          opacity={0.88}
          depthTest={false}
          depthWrite={false}
          side={THREE.DoubleSide}
          toneMapped={false}
        />
      </mesh>
    </group>
  );
}

export function Ball({
  position = [0, 112, 0],
  interactive = true,
  renderOnly = false,
  aimEnabled = false,
  aimDraft = null,
  kickControlEnvelope = null,
  onAimChange,
  onAimRelease,
  renderGroupRef,
}: BallProps) {
  const { nodes } = useGLTF(
    "/models/in-game/Ball/Ball.glb",
  ) as unknown as GLTFResult;
  const rigidBodyRef = useRef<RapierRigidBody>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState<THREE.Vector3 | null>(null);
  const [dragCurrent, setDragCurrent] = useState<THREE.Vector3 | null>(null);
  const { camera } = useThree();
  const readableBallMaterial = useMemo<
    THREE.Material | THREE.Material[]
  >(() => {
    const configure = (source: THREE.Material) => {
      const material = source.clone();
      material.depthTest = false;
      material.depthWrite = false;
      return material;
    };

    return Array.isArray(nodes.Ball.material)
      ? nodes.Ball.material.map(configure)
      : configure(nodes.Ball.material);
  }, [nodes.Ball.material]);

  useEffect(() => {
    const materials = Array.isArray(readableBallMaterial)
      ? readableBallMaterial
      : [readableBallMaterial];

    return () => materials.forEach((material) => material.dispose());
  }, [readableBallMaterial]);

  const handlePointerDown = (e: ThreeEvent<PointerEvent>) => {
    if (!interactive && !aimEnabled) return;
    // Prevent camera controls from taking over
    e.stopPropagation();

    // In React Three Fiber, event.point is the 3D interaction point
    // using the event's ray intersection
    if (rigidBodyRef.current && !renderOnly) {
      // Stop the ball momentarily to aim? Optional, but helpful.
      rigidBodyRef.current.setLinvel({ x: 0, y: 0, z: 0 }, true);
      rigidBodyRef.current.setAngvel({ x: 0, y: 0, z: 0 }, true);
    }

    setIsDragging(true);
    setDragStart(e.point.clone());
    setDragCurrent(e.point.clone());
    onAimChange?.(null);

    // Capture pointer to track outside mesh
    (e.target as unknown as PointerCaptureTarget).setPointerCapture(
      e.pointerId,
    );
  };

  const handlePointerMove = (e: ThreeEvent<PointerEvent>) => {
    if (!interactive && !aimEnabled) return;
    if (!isDragging || !dragStart) return;

    // We need to raycast to a "virtual floor" plane at the ball's height
    // to get consistent dragging even if we move off the ball mesh
    const floorPlane = new THREE.Plane(
      new THREE.Vector3(0, 1, 0),
      -dragStart.y,
    );
    const raycaster = new THREE.Raycaster();
    raycaster.setFromCamera(e.pointer, camera);
    const intersectPoint = new THREE.Vector3();

    // Check intersection with our horizontal plane
    if (raycaster.ray.intersectPlane(floorPlane, intersectPoint)) {
      setDragCurrent(intersectPoint);
      onAimChange?.(buildBallAimDraft(dragStart, intersectPoint));
    }
  };

  const handlePointerUp = (e: ThreeEvent<PointerEvent>) => {
    if (!interactive && !aimEnabled) return;
    if (!isDragging || !dragStart || !dragCurrent) return;

    setIsDragging(false);
    (e.target as unknown as PointerCaptureTarget).releasePointerCapture(
      e.pointerId,
    );

    const releasedAimDraft = buildBallAimDraft(dragStart, dragCurrent);

    if (
      interactive &&
      rigidBodyRef.current &&
      !renderOnly &&
      releasedAimDraft
    ) {
      const impulse = new THREE.Vector3(
        releasedAimDraft.shotVector.x,
        releasedAimDraft.shotVector.y,
        releasedAimDraft.shotVector.z,
      ).multiplyScalar(10.0);
      impulse.y = Math.abs(impulse.y) * 0.1;
      rigidBodyRef.current.applyImpulse(impulse, true);
    }

    if (releasedAimDraft) {
      onAimRelease?.(releasedAimDraft);
    } else {
      onAimChange?.(null);
    }

    setDragStart(null);
    setDragCurrent(null);
  };

  const handlePointerCancel = (e: ThreeEvent<PointerEvent>) => {
    if (!isDragging) return;
    setIsDragging(false);
    (e.target as unknown as PointerCaptureTarget).releasePointerCapture(
      e.pointerId,
    );
    setDragStart(null);
    setDragCurrent(null);
    onAimChange?.(null);
  };

  // Calculate arrow direction and length
  const arrowData = useMemo(() => {
    const currentAimDraft =
      aimDraft ||
      (isDragging && dragStart && dragCurrent
        ? buildBallAimDraft(dragStart, dragCurrent)
        : null);
    if (!currentAimDraft) return null;

    // Direction from dragCurrent (pull position) to dragStart (ball position)
    // This shows where the ball will go
    const direction = new THREE.Vector3(
      currentAimDraft.shotVector.x,
      currentAimDraft.shotVector.y,
      currentAimDraft.shotVector.z,
    );
    const usablePowerRatio = kickControlEnvelope
      ? visibleKickPowerRatio(
          kickControlEnvelope,
          currentAimDraft.normalizedPower,
        )
      : currentAimDraft.normalizedPower;
    let length = AIM_VISIBLE_ARROW_MAX_LENGTH * usablePowerRatio;

    // Minimum length to show arrow
    if (length < 0.1) return null;
    if (length > AIM_VISIBLE_ARROW_MAX_LENGTH)
      length = AIM_VISIBLE_ARROW_MAX_LENGTH;

    direction.y = 0;
    direction.normalize();
    // Keep the complete silhouette on the pitch plane. setFromUnitVectors leaves
    // roll unconstrained, which can turn a diagonal arrow edge-on to the camera.
    const surfaceNormal = new THREE.Vector3(0, 1, 0);
    const right = new THREE.Vector3()
      .crossVectors(direction, surfaceNormal)
      .normalize();
    const quaternion = new THREE.Quaternion().setFromRotationMatrix(
      new THREE.Matrix4().makeBasis(right, direction, surfaceNormal),
    );

    return {
      position: new THREE.Vector3(
        currentAimDraft.dragStart.x,
        currentAimDraft.dragStart.y,
        currentAimDraft.dragStart.z,
      ),
      direction,
      length,
      quaternion,
    };
  }, [aimDraft, dragCurrent, dragStart, isDragging, kickControlEnvelope]);

  if (renderOnly) {
    return (
      <group ref={renderGroupRef} dispose={null} position={position}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ball.geometry}
          material={readableBallMaterial}
          renderOrder={5}
          scale={BALL_MODEL_REGISTRATION.visualScale}
          onPointerDown={aimEnabled ? handlePointerDown : undefined}
          onPointerMove={aimEnabled ? handlePointerMove : undefined}
          onPointerUp={aimEnabled ? handlePointerUp : undefined}
          onPointerCancel={aimEnabled ? handlePointerCancel : undefined}
        >
          <Outlines
            thickness={0.03}
            color={BALL_READABILITY_OUTLINE}
            angle={0}
          />
        </mesh>
        <BallReadabilityIndicator />
        {arrowData && (
          <AimArrow
            position={[
              arrowData.position.x + 0.1 - position[0],
              arrowData.position.y - position[1],
              arrowData.position.z - position[2],
            ]}
            quaternion={arrowData.quaternion}
            length={arrowData.length}
          />
        )}
      </group>
    );
  }

  return (
    <group dispose={null}>
      <RigidBody
        position={position}
        scale={0.5}
        ref={rigidBodyRef}
        colliders="ball"
        restitution={0.8}
        friction={1.0}
        linearDamping={0.5}
        angularDamping={0.5}
        name="ball"
        type={interactive ? "dynamic" : "fixed"}
        gravityScale={interactive ? 1 : 0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ball.geometry}
          material={readableBallMaterial}
          renderOrder={5}
          onPointerDown={interactive ? handlePointerDown : undefined}
          onPointerMove={interactive ? handlePointerMove : undefined}
          onPointerUp={interactive ? handlePointerUp : undefined}
          // No position prop needed - mesh follows RigidBody automatically
        >
          <Outlines
            thickness={0.03}
            color={BALL_READABILITY_OUTLINE}
            angle={0}
          />
        </mesh>
        <BallReadabilityIndicator />
      </RigidBody>

      {/* Arrow indicator showing shot direction and strength */}
      {arrowData && (
        <AimArrow
          position={[
            arrowData.position.x + 0.1,
            arrowData.position.y,
            arrowData.position.z,
          ]}
          quaternion={arrowData.quaternion}
          length={arrowData.length}
        />
      )}
    </group>
  );
}
