/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Outlines, useGLTF, useTexture } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { JSX, useMemo } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import {
  registeredEmbeddedGoalFrameX,
  STADIUM_REGISTRATION,
} from "../../../match/stadium-registration";

const TURF_TEXTURE_PATH = "/models/in-game/textures/pitch/overgoal-turf.webp";
const TURF_TEXTURE_REPEAT: [number, number] = [3.5, 5.4];

type GLTFResult = GLTF & {
  nodes: {
    Stadiump1: THREE.Mesh;
    Stadiump2: THREE.Mesh;
    Barriers: THREE.Mesh;
    GoalNet: THREE.Mesh;
    PitchBanner: THREE.Mesh;
    Grass_mesh: THREE.Mesh;
    Pitch_mesh: THREE.Mesh;
  };
  materials: {
    PitchDraw: THREE.MeshStandardMaterial;
  };
};

export default function Stadium(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/models/in-game/ST.glb") as unknown as GLTFResult;

  const alphaMap = useTexture(
    "/models/in-game/textures/pitch/regulation-lines.svg",
  );
  const netTexture = useTexture("/models/in-game/Net.png");
  const turfTexture = useTexture(TURF_TEXTURE_PATH);

  const pitchMaterial = useMemo(() => {
    const material = new THREE.MeshStandardMaterial();
    material.side = THREE.DoubleSide;
    material.emissive.set("#0088ff");
    material.transparent = true;
    material.alphaMap = alphaMap;
    material.opacity = 0.6;

    return material;
  }, [alphaMap]);

  const netMaterial = useMemo(() => {
    const material = new THREE.MeshStandardMaterial();
    material.side = THREE.DoubleSide;
    material.emissive.set("#ff5a00");
    material.emissiveIntensity = 200;
    material.transparent = true;
    material.alphaMap = netTexture;
    material.opacity = 0.6;
    return material;
  }, [netTexture]);

  const stadiumGeometry = useMemo(() => {
    const geometry = nodes.Stadiump1.geometry.clone();
    const positions = geometry.attributes.position;
    for (let index = 0; index < positions.count; index += 1) {
      const x = positions.getX(index);
      positions.setX(
        index,
        registeredEmbeddedGoalFrameX(x, positions.getZ(index)),
      );
    }
    positions.needsUpdate = true;
    geometry.computeBoundingBox();
    geometry.computeBoundingSphere();
    return geometry;
  }, [nodes.Stadiump1.geometry]);

  const grassMaterial = useMemo(() => {
    const originalMat = nodes.Grass_mesh.material as THREE.MeshStandardMaterial;
    const mat = originalMat.clone();
    const map = turfTexture.clone();
    map.wrapS = THREE.RepeatWrapping;
    map.wrapT = THREE.RepeatWrapping;
    map.colorSpace = THREE.SRGBColorSpace;
    map.repeat.set(...TURF_TEXTURE_REPEAT);
    map.offset.set(0, 0);
    map.anisotropy = 8;
    map.needsUpdate = true;

    mat.map = map;
    mat.color.set("#ffffff");
    mat.needsUpdate = true;
    return mat;
  }, [nodes.Grass_mesh.material, turfTexture]);

  return (
    <group {...props} dispose={null}>
      <group
        position={STADIUM_REGISTRATION.position}
        scale={STADIUM_REGISTRATION.scale}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={stadiumGeometry}
          material={nodes.Stadiump1.material}
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stadiump2.geometry}
          material={nodes.Stadiump2.material}
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Barriers.geometry}
          material={nodes.Barriers.material}
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GoalNet.geometry}
          material={netMaterial}
          scale={STADIUM_REGISTRATION.goalMeshScale}
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PitchBanner.geometry}
          material={nodes.PitchBanner.material}
        ></mesh>
        <RigidBody type="fixed" colliders="trimesh">
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grass_mesh.geometry}
            material={grassMaterial}
            position={[0, 0.2, 0]}
            scale={[1525.289, 50.843, 2287.934]}
          />
        </RigidBody>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pitch_mesh.geometry}
          material={pitchMaterial}
          position={[0, 0.2, 0]}
          scale={[1525.289, 50.843, 2287.934]}
        ></mesh>
      </group>
    </group>
  );
}
